version: '3.3'

services:
  database:
    image: postgres:latest
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: exchange_market
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
 